### ISSUE TITLE
Peer Review 1 Sydney St Clair

### ISSUE THREAD

**Issue by stclassy** [erickr19/scent-dex#2]
@erickr19 

Problem Statement:

I like a short and sweet statement! Consider adding just a little more detail, are users able to upload scents? Can the leave their own description or comment on their review or is it going to be a star based system? Also work your What, Why, and How into the whole statement instead of segments, that way it's more of an elevator pitch than a bullet list.

Design Documentation:

Wow you put a lot of work into your wire frames they looks amazing! Consider creating a screens.md and link your images to the file, that way the images are all in one file and the width is more fixed. You have great user stories! Consider building out an application flow for the user stories. It will help you determine how many servlet's and jsp's you are going to need. Look at the FatBikeTire repo on GitHub for some really good examples and if you look at the raw for the .md files you can see how they are formatted.

Data model/Database:

No file uploaded currently and it looks like you haven't gotten to adding another table yet. When you do, make sure to add on update and on delete rules so if a user deletes their account, their wishlist isn't continued to be stored.

Code:

Good project structure, but your .gitignore file should be out one more directory! It's in your .idea directory, which should be ignored. If you move it out into the scent-dex directory, github will start ignoring those files! Jsp's look great! Only thing I can see is that you have your nav bar built, but don't include it on your jsp's. Just wanted to remind you you need to use the include tag for each file you want to be included. You could reduce some potentially redundant code by including an end page jsp to include in each file as well! We should only write that stuff once to save on time and let the computer do the hard work! 

Great project idea! I can't wait to see how snazzy you can make it! I always got a little frustrated with front end development but you seem to have a real good understanding! Any tips for a fellow coder in learning?

**Comment by pawaitemadisoncollege** [comment]
Hi @stclassy Thanks for your thorough review here! Your review shows a keen eye to the details that should help @erickr19 make some solid improvements in several areas. Good work!!!
